---
- name: Atualiza Certificado SSL (Let's Engrypt)
  hosts: '{{target|default("ESUS_PROD")}}'
  remote_user: '{{user|default("ansible_ssh_user")}}' 
  vars:
    senhap12: '{{pw12|default(p12_pw_esus)}}'
    dominio: '{{url|default(url_esus)}}'
    path_esus: '/opt/e-SUS/webserver/config/'

  tasks:
  #task
  - name: Verifica versao do OpenSSL
    ansible.builtin.package_facts:
      manager: auto
    
  #task 0
  - name: Verifica Apache
    ansible.builtin.systemd_service:
      name: apache2.service
    register: status_apache

  - name: debug status apache 
    ansible.builtin.debug:
      var: status_apache.status.ActiveState
  
  #task 1
  - name: Parando Apache
    ansible.builtin.service:
      name: apache2.service
      state: stopped
    become: yes
    become_method: sudo
    register: status_apache
    when: status_apache.status.ActiveState == "active"

  #task 2
  - name: Renova Certbot - Let's Engrypt
    ansible.builtin.command:
      cmd: certbot renew
    become: yes
    become_method: sudo

  #task 2.1
  - name: Convert chave para p12
    ansible.builtin.command:
      cmd: openssl
           pkcs12 -export
           -in fullchain.pem 
           -inkey privkey.pem 
           -out {{path_esus}}esusaps.p12 
           -name "esusaps" 
           -CAfile chain.pem 
           -caname esusaps 
           -passout pass:{{senhap12}}
    args:
      chdir: '/etc/letsencrypt/live/{{dominio}}'
    become: yes
    become_method: sudo
    register: p12_gerada
    ignore_errors: true
    when: "'1.1.1f-1ubuntu' in ansible_facts.packages.openssl[0].version"

  #task 2.1
  - name: Convert chave para p12:jks
    ansible.builtin.command:
      cmd: openssl
           pkcs12 -export
           -in fullchain.pem 
           -inkey privkey.pem 
           -out {{path_esus}}esusaps.p12 
           -name "esusaps"
           -passout pass:{{senhap12}}
    args:
      chdir: '/etc/letsencrypt/live/{{dominio}}'
    become: yes
    become_method: sudo
    register: p12_gerada
    ignore_errors: true
    when: "'3.0' in ansible_facts.packages.openssl[0].version"

  #task 2.1.1
  - name: Verifica se esusaps.jks já existe
    ansible.builtin.stat:
    args:
     name: '{{path_esus}}esusaps.jks'
    become: yes
    become_method: sudo
    register: jks_exist
    ignore_errors: true
    when: "'3.0' in ansible_facts.packages.openssl[0].version"

  #task 2.1.2
  - name: Apagar jks
    ansible.builtin.command:
      cmd: keytool 
         -delete -alias esusaps 
         -keystore {{path_esus}}esusaps.jks
         -storetype JKS 
         -storepass {{senhap12}}
    become: yes
    become_method: sudo
    register: jks_gerada
    ignore_errors: true
    when:
      - "'3.0' in ansible_facts.packages.openssl[0].version"
      - jks_exist.stat.exists is true 

  #task 2.1.2
  - name: Gerando jks
    ansible.builtin.command:
      cmd: keytool 
          -importkeystore 
          -srckeystore {{path_esus}}esusaps.p12 
          -srcstoretype PKCS12 
          -destkeystore {{path_esus}}esusaps.jks 
          -deststoretype JKS 
          -deststorepass {{senhap12}} -srcstorepass {{senhap12}}
    become: yes
    become_method: sudo
    register: jks_gerada
    ignore_errors: true
    when:
      - p12_gerada.changed is true 
      - "'3.0' in ansible_facts.packages.openssl[0].version"

  #task 3
  - name: Iniciando Apache
    ansible.builtin.service:
      name: apache2.service
      state: started
    become: yes
    become_method: sudo
    register: status_apache

  #task 4
  - name: Parando e-SUS
    ansible.builtin.service:
      name: e-SUS-PEC.service
      state: stopped
    become: yes
    become_method: sudo

  #task 5
  - name: Inciando e-SUS
    ansible.builtin.service:
      name: e-SUS-PEC.service
      state: started
    become: yes
    become_method: sudo
...